"""Spawn the env-prepared subshell + emit shell activation hooks.

Two distinct UX surfaces live here:

  :func:`spawn_subshell`
    Used by ``llmstack start`` and ``llmstack shell``. ``execvp``s into
    the user's ``$SHELL`` with ``OPENCODE_CONFIG`` and friends exported
    so ``opencode`` -- and any other tool -- picks up our local stack
    inside that one terminal only. For zsh and bash we also write a
    transient rcfile that sources the user's normal rc and prefixes the
    prompt with ``[llmstack:<channel>]``.

  :func:`activate_hook`
    Used by ``llmstack activate <shell>``. Emits a self-contained
    snippet the user pastes into their shell rc once. The snippet walks
    up from ``$PWD`` on every prompt to find the nearest
    ``.llmstack/opencode.json`` and toggles the env vars + prompt
    prefix accordingly. Independent of the spawn flow above.
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

from llmstack._platform import IS_WINDOWS, default_shell, shell_family
from llmstack.paths import PACKAGE_DIR, remote_url, resolve

# 256-colour palette:
#   current  = steel-blue    (38)   -- our local stack, canonical channel
#   next     = orange        (208)  -- our local stack, queued upgrade channel
#   external = medium-purple (135)  -- thin client of a remote llmstack
#                                      (LLMSTACK_REMOTE_URL is set)
#   shared   = yellow        (220)  -- local daemons we don't own (started
#                                      by another project on this host)
COLOR_CODE = {"current": 38, "next": 208, "external": 135, "shared": 220}


def _user_shell() -> tuple[str, str]:
    """Return ``(absolute path to shell, basename like ``zsh`` / ``pwsh``)``.

    Resolution lives in :func:`llmstack._platform.default_shell` so the
    POSIX vs Windows differences (``$SHELL`` vs ``$ComSpec``,
    ``/bin/bash`` vs ``pwsh.exe`` fallback) stay in one place.
    """
    return default_shell()


def _llmstack_alias_target() -> str:
    """Best path to invoke ``llmstack`` from inside the spawned shell.

    Prefers the console-script on ``PATH`` (``pip install`` provides one);
    falls back to ``python -m llmstack`` so an editable / non-console
    install still works.
    """
    found = shutil.which("llmstack")
    if found:
        return found
    return f"{sys.executable} -m llmstack"


def _prompt_label(channel: str, url: str | None) -> str:
    """Text inside ``[llmstack:...]`` -- ``external`` keeps the URL visible."""
    if channel == "external" and url:
        return f"{channel} {url}"
    return channel


def _write_bash_rcfile(rcfile: Path, channel: str, color: int, alias_target: str, label: str) -> None:
    rcfile.write_text(
        "# AUTO-GENERATED by llmstack; sourced by the spawned subshell.\n"
        '[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"\n'
        f"alias llmstack='{alias_target}'\n"
        f'PS1="\\[\\033[38;5;{color}m\\][llmstack:{label}]\\[\\033[0m\\] ${{PS1:-\\$ }}"\n'
    )


def _write_zsh_rcfile(zdotdir: Path, channel: str, color: int, alias_target: str, label: str) -> None:
    zdotdir.mkdir(parents=True, exist_ok=True)
    (zdotdir / ".zshrc").write_text(
        "# AUTO-GENERATED by llmstack; sourced by the spawned subshell.\n"
        '[ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc"\n'
        f"alias llmstack='{alias_target}'\n"
        f'PROMPT="%F{{{color}}}[llmstack:{label}]%f ${{PROMPT:-%# }}"\n'
    )


# --- Windows: PowerShell host file + a tiny cmd batch wrapper -------------
#
# PowerShell wants a $PROFILE-shaped script to run on startup; we point
# the host's ``-NoExit -File`` at our generated profile so the user's
# normal $PROFILE still runs first, then we layer our prompt + alias on
# top. cmd.exe gets a much simpler treatment via ``/k`` + a one-shot
# batch script.

_POWERSHELL_PROFILE_TEMPLATE = """\
# AUTO-GENERATED by llmstack; loaded by the spawned subshell.
# Run the user's normal profile first so their aliases survive.
foreach ($p in @($PROFILE.AllUsersAllHosts, $PROFILE.AllUsersCurrentHost,
                  $PROFILE.CurrentUserAllHosts, $PROFILE.CurrentUserCurrentHost)) {{
    if ($p -and (Test-Path $p)) {{ . $p }}
}}

function global:llmstack {{ {alias_invocation} }}

function global:prompt {{
    $esc = [char]27
    Write-Host -NoNewline "${{esc}}[38;5;{color}m[llmstack:{label}]${{esc}}[0m "
    "PS " + (Get-Location) + "> "
}}
"""


_CMD_BATCH_TEMPLATE = """\
@echo off
REM AUTO-GENERATED by llmstack; loaded by the spawned subshell.
doskey llmstack={alias_invocation} $*
prompt [llmstack:{label}] $P$G
"""


def _alias_invocation_powershell(alias_target: str) -> str:
    """Build the body of the PowerShell ``llmstack`` function."""
    if alias_target.startswith(sys.executable):
        # ``python -m llmstack`` -- pass through unchanged, args are forwarded.
        return f"& '{sys.executable}' -m llmstack @args"
    return f"& '{alias_target}' @args"


def _alias_invocation_cmd(alias_target: str) -> str:
    """``doskey`` macro body. Quote the executable, strip the args sentinel."""
    if alias_target.startswith(sys.executable):
        return f'"{sys.executable}" -m llmstack'
    return f'"{alias_target}"'


def _write_powershell_profile(target: Path, color: int, alias_target: str, label: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_POWERSHELL_PROFILE_TEMPLATE.format(
        color=color,
        label=label,
        alias_invocation=_alias_invocation_powershell(alias_target),
    ))


def _write_cmd_batch(target: Path, alias_target: str, label: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_CMD_BATCH_TEMPLATE.format(
        label=label,
        alias_invocation=_alias_invocation_cmd(alias_target),
    ))


def spawn_subshell(channel: str, *, reload: bool = False) -> None:
    """Replace the current process with an interactive shell carrying our env.

    Refuses re-entry into a nested llmstack shell unless ``reload=True``
    (used by ``start`` to swap channels in-place).
    """
    paths = resolve()
    if not paths.opencode_json.is_file():
        raise SystemExit(f"missing {paths.opencode_json} (run: llmstack install)")

    if os.environ.get("LLMSTACK_ACTIVE") == "1" and not reload:
        print(
            f"[!] already inside an llmstack shell (channel: {os.environ.get('LLMSTACK_CHANNEL', '?')}).",
            file=sys.stderr,
        )
        print("    exit this shell first if you want to start a new one.", file=sys.stderr)
        raise SystemExit(1)

    user_shell, shell_name = _user_shell()
    family = shell_family(shell_name)
    color = COLOR_CODE.get(channel, COLOR_CODE["current"])
    alias_target = _llmstack_alias_target()

    rurl = remote_url()
    label = _prompt_label(channel, rurl)
    print()
    print(f"[*] entering llmstack subshell (channel: {channel}, shell: {shell_name})")
    print(f"    OPENCODE_CONFIG -> {paths.opencode_json}")
    if rurl:
        print(f"    remote          -> {rurl}")
    print(f"    alias 'llmstack' -> {alias_target}")
    if channel == "external":
        print("    remote daemons keep running on exit; nothing local to stop.")
    else:
        print("    daemons keep running on exit; stop them with: llmstack stop")
    print("    second window?: llmstack shell")
    print()

    env = {**os.environ}
    if family == "bash":
        rcfile = paths.state_dir / "llmstack.bashrc"
        _write_bash_rcfile(rcfile, channel, color, alias_target, label)
        argv = [user_shell, "--rcfile", str(rcfile), "-i"]
    elif family == "zsh":
        zdotdir = paths.state_dir / "zdotdir"
        _write_zsh_rcfile(zdotdir, channel, color, alias_target, label)
        argv = [user_shell, "-i"]
        env["ZDOTDIR"] = str(zdotdir)
    elif family == "powershell":
        profile = paths.state_dir / "llmstack.profile.ps1"
        _write_powershell_profile(profile, color, alias_target, label)
        argv = [
            user_shell,
            "-NoLogo",
            "-NoExit",
            "-ExecutionPolicy", "Bypass",
            "-File", str(profile),
        ]
    elif family == "cmd":
        batch = paths.state_dir / "llmstack.cmd"
        _write_cmd_batch(batch, alias_target, label)
        argv = [user_shell, "/k", str(batch)]
    else:
        # Unknown POSIX-shaped shell -- best-effort: just ``-i``, no prompt.
        argv = [user_shell, "-i"]

    env.update({
        "OPENCODE_CONFIG": str(paths.opencode_json),
        "LLMSTACK_CHANNEL": channel,
        "LLMSTACK_ACTIVE": "1",
        "LLMSTACK_ROOT": str(PACKAGE_DIR),
    })
    if rurl:
        env["LLMSTACK_REMOTE_URL"] = rurl

    if IS_WINDOWS:
        # ``execvpe`` is emulated on Windows and behaves oddly when the
        # parent is a non-console process; ``subprocess.run`` is more
        # predictable and lets the user actually exit back to the
        # parent shell.
        import subprocess
        rc = subprocess.run(argv, env=env).returncode
        raise SystemExit(rc)
    os.execvpe(argv[0], argv, env)


# --- activate hooks -------------------------------------------------------

_ZSH_HOOK = r"""# --- llmstack auto-activation hook (zsh) -----------------------------------
# Generated by `llmstack activate zsh`. Walks up from $PWD on each
# directory change to find the nearest .llmstack/opencode.json. Reads the
# project's channel marker (active-channel, falling back to
# default-channel) and exports OPENCODE_CONFIG, LLMSTACK_PROJECT,
# LLMSTACK_CHANNEL, and -- when channel == external -- LLMSTACK_REMOTE_URL.
# Reverses everything when you step out.
#
# Marker file format (one line):
#   <channel>[ <url>]
#
# Prompt colour by channel:
#   current  -> steel-blue    (local stack, canonical)
#   next     -> orange        (local stack, queued upgrade)
#   external -> medium-purple (remote stack via LLMSTACK_REMOTE_URL)
#   shared   -> yellow        (local daemons started by another project)
# In external mode the URL is appended to the prompt label so you always
# see which remote you're talking to: [llmstack:<project> <url>]

_llmstack_find_root() {
    local dir="${1:-$PWD}"
    while [[ "$dir" != "/" && -n "$dir" ]]; do
        if [[ -f "$dir/.llmstack/opencode.json" ]]; then
            print -r -- "$dir"
            return 0
        fi
        dir="${dir:h}"
    done
    return 1
}

_llmstack_color() {
    case "${1:-current}" in
        next)     print -r -- 208 ;;
        external) print -r -- 135 ;;
        shared)   print -r -- 220 ;;
        *)        print -r -- 38  ;;
    esac
}

_llmstack_read_marker() {
    # Read "<channel> [url]" from $1 into _ch / _url. Sets _ch="" on failure.
    _ch=""; _url=""
    [[ -f "$1" ]] || return 0
    read -r _ch _url < "$1" || true
}

_llmstack_activate() {
    local found
    found="$(_llmstack_find_root)" || found=""

    if [[ -n "$found" ]]; then
        # entering or moving within a project
        if [[ "${LLMSTACK_PROJECT:-}" != "$found" ]]; then
            export OPENCODE_CONFIG="$found/.llmstack/opencode.json"
            export LLMSTACK_PROJECT="$found"
            export LLMSTACK_ACTIVE="1"

            local _ch _url
            # Channel resolution: live (active-channel, written by `start`)
            # > intent (default-channel, written by `install`) > "current".
            if [[ -f "$found/.llmstack/active-channel" ]]; then
                _llmstack_read_marker "$found/.llmstack/active-channel"
            else
                _llmstack_read_marker "$found/.llmstack/default-channel"
            fi
            : "${_ch:=current}"
            export LLMSTACK_CHANNEL="$_ch"
            if [[ "$_ch" == "external" && -n "$_url" ]]; then
                export LLMSTACK_REMOTE_URL="$_url"
            else
                unset LLMSTACK_REMOTE_URL
            fi

            : "${_LLMSTACK_PS1_BACKUP:=$PROMPT}"
            export _LLMSTACK_PS1_BACKUP
            local label color suffix
            label="${found:t}"
            color="$(_llmstack_color "$_ch")"
            if [[ "$_ch" == "external" && -n "$_url" ]]; then
                suffix=" $_url"
            else
                suffix=""
            fi
            PROMPT="%F{${color}}[llmstack:${label}${suffix}]%f $_LLMSTACK_PS1_BACKUP"
        fi
    else
        # leaving any project
        if [[ -n "${LLMSTACK_PROJECT:-}" ]]; then
            unset OPENCODE_CONFIG LLMSTACK_PROJECT LLMSTACK_ACTIVE LLMSTACK_CHANNEL LLMSTACK_REMOTE_URL
            if [[ -n "${_LLMSTACK_PS1_BACKUP:-}" ]]; then
                PROMPT="$_LLMSTACK_PS1_BACKUP"
                unset _LLMSTACK_PS1_BACKUP
            fi
        fi
    fi
}

# Hook on every directory change AND once for the current shell.
autoload -U add-zsh-hook
add-zsh-hook chpwd _llmstack_activate
_llmstack_activate
# --- end llmstack hook -----------------------------------------------------
"""

_BASH_HOOK = r"""# --- llmstack auto-activation hook (bash) ----------------------------------
# Generated by `llmstack activate bash`. Walks up from $PWD on each prompt
# to find the nearest .llmstack/opencode.json. Reads the project's channel
# marker (active-channel, falling back to default-channel) and exports
# OPENCODE_CONFIG, LLMSTACK_PROJECT, LLMSTACK_CHANNEL, and -- when
# channel == external -- LLMSTACK_REMOTE_URL. Reverses everything when
# you step out.
#
# Marker file format (one line):
#   <channel>[ <url>]
#
# Prompt colour by channel:
#   current  -> steel-blue    (local stack, canonical)
#   next     -> orange        (local stack, queued upgrade)
#   external -> medium-purple (remote stack via LLMSTACK_REMOTE_URL)
#   shared   -> yellow        (local daemons started by another project)
# In external mode the URL is appended to the prompt label so you always
# see which remote you're talking to: [llmstack:<project> <url>]

_llmstack_find_root() {
    local dir="${1:-$PWD}"
    while [[ "$dir" != "/" && -n "$dir" ]]; do
        if [[ -f "$dir/.llmstack/opencode.json" ]]; then
            printf '%s\n' "$dir"
            return 0
        fi
        dir="$(dirname "$dir")"
    done
    return 1
}

_llmstack_color() {
    case "${1:-current}" in
        next)     printf '%s' 208 ;;
        external) printf '%s' 135 ;;
        shared)   printf '%s' 220 ;;
        *)        printf '%s' 38  ;;
    esac
}

_llmstack_read_marker() {
    _ch=""; _url=""
    [[ -f "$1" ]] || return 0
    read -r _ch _url < "$1" || true
}

_llmstack_activate() {
    local found
    found="$(_llmstack_find_root)" || found=""

    if [[ -n "$found" ]]; then
        if [[ "${LLMSTACK_PROJECT:-}" != "$found" ]]; then
            export OPENCODE_CONFIG="$found/.llmstack/opencode.json"
            export LLMSTACK_PROJECT="$found"
            export LLMSTACK_ACTIVE="1"

            local _ch _url
            # Channel resolution: live > intent > "current" (see zsh hook).
            if [[ -f "$found/.llmstack/active-channel" ]]; then
                _llmstack_read_marker "$found/.llmstack/active-channel"
            else
                _llmstack_read_marker "$found/.llmstack/default-channel"
            fi
            : "${_ch:=current}"
            export LLMSTACK_CHANNEL="$_ch"
            if [[ "$_ch" == "external" && -n "$_url" ]]; then
                export LLMSTACK_REMOTE_URL="$_url"
            else
                unset LLMSTACK_REMOTE_URL
            fi

            : "${_LLMSTACK_PS1_BACKUP:=$PS1}"
            export _LLMSTACK_PS1_BACKUP
            local label color suffix
            label="$(basename "$found")"
            color="$(_llmstack_color "$_ch")"
            if [[ "$_ch" == "external" && -n "$_url" ]]; then
                suffix=" $_url"
            else
                suffix=""
            fi
            PS1="\[\033[38;5;${color}m\][llmstack:${label}${suffix}]\[\033[0m\] $_LLMSTACK_PS1_BACKUP"
        fi
    else
        if [[ -n "${LLMSTACK_PROJECT:-}" ]]; then
            unset OPENCODE_CONFIG LLMSTACK_PROJECT LLMSTACK_ACTIVE LLMSTACK_CHANNEL LLMSTACK_REMOTE_URL
            if [[ -n "${_LLMSTACK_PS1_BACKUP:-}" ]]; then
                PS1="$_LLMSTACK_PS1_BACKUP"
                unset _LLMSTACK_PS1_BACKUP
            fi
        fi
    fi
}

# Bash has no chpwd hook, so we run on every prompt. Idempotent: if the
# project hasn't changed, we no-op.
case ";${PROMPT_COMMAND:-};" in
    *";_llmstack_activate;"*) ;;
    *) PROMPT_COMMAND="_llmstack_activate;${PROMPT_COMMAND:-}" ;;
esac
_llmstack_activate
# --- end llmstack hook -----------------------------------------------------
"""


_POWERSHELL_HOOK = r"""# --- llmstack auto-activation hook (PowerShell) ----------------------------
# Generated by `llmstack activate powershell`. Walks up from $PWD on each
# prompt to find the nearest .llmstack/opencode.json. Reads the project's
# channel marker (active-channel, falling back to default-channel) and
# exports OPENCODE_CONFIG, LLMSTACK_PROJECT, LLMSTACK_CHANNEL, and --
# when channel == external -- LLMSTACK_REMOTE_URL. Reverses everything
# when you cd out of the project.
#
# Add to your $PROFILE (one time):
#     llmstack activate powershell | Out-String | Invoke-Expression
# or, to persist across sessions:
#     "Invoke-Expression (& llmstack activate powershell | Out-String)" | Add-Content $PROFILE
#
# Marker file format (one line):
#   <channel>[ <url>]
#
# Prompt colour by channel:
#   current  -> steel-blue    (38)
#   next     -> orange        (208)
#   external -> medium-purple (135)
#   shared   -> yellow        (220)

function global:_LlmstackFindRoot {
    param([string]$Start = (Get-Location).Path)
    $dir = $Start
    while ($dir -and (Test-Path $dir)) {
        if (Test-Path -LiteralPath (Join-Path $dir ".llmstack/opencode.json")) {
            return $dir
        }
        $parent = Split-Path -Parent $dir
        if ($parent -eq $dir) { break }
        $dir = $parent
    }
    return $null
}

function global:_LlmstackChannelColor {
    param([string]$Channel)
    switch ($Channel) {
        "next"     { 208 }
        "external" { 135 }
        "shared"   { 220 }
        default    { 38  }
    }
}

function global:_LlmstackReadMarker {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return @{ channel = ""; url = "" } }
    $line = (Get-Content -LiteralPath $Path -TotalCount 1) -as [string]
    if (-not $line) { return @{ channel = ""; url = "" } }
    $parts = $line.Trim() -split '\s+', 2
    return @{
        channel = $parts[0]
        url     = if ($parts.Length -gt 1) { $parts[1] } else { "" }
    }
}

function global:_LlmstackActivate {
    $found = _LlmstackFindRoot
    if ($found) {
        if ($env:LLMSTACK_PROJECT -ne $found) {
            $env:OPENCODE_CONFIG  = Join-Path $found ".llmstack/opencode.json"
            $env:LLMSTACK_PROJECT = $found
            $env:LLMSTACK_ACTIVE  = "1"

            $live    = Join-Path $found ".llmstack/active-channel"
            $intent  = Join-Path $found ".llmstack/default-channel"
            $marker  = if (Test-Path -LiteralPath $live) { _LlmstackReadMarker $live } else { _LlmstackReadMarker $intent }
            $channel = if ($marker.channel) { $marker.channel } else { "current" }
            $env:LLMSTACK_CHANNEL = $channel
            if ($channel -eq "external" -and $marker.url) {
                $env:LLMSTACK_REMOTE_URL = $marker.url
            } else {
                Remove-Item Env:LLMSTACK_REMOTE_URL -ErrorAction SilentlyContinue
            }

            $global:_LLMSTACK_PROMPT_COLOR  = _LlmstackChannelColor $channel
            $global:_LLMSTACK_PROMPT_LABEL  = Split-Path $found -Leaf
            $global:_LLMSTACK_PROMPT_SUFFIX = if ($channel -eq "external" -and $marker.url) { " " + $marker.url } else { "" }
            $global:_LLMSTACK_PROMPT_ON     = $true
        }
    } elseif ($env:LLMSTACK_PROJECT) {
        Remove-Item Env:OPENCODE_CONFIG    -ErrorAction SilentlyContinue
        Remove-Item Env:LLMSTACK_PROJECT   -ErrorAction SilentlyContinue
        Remove-Item Env:LLMSTACK_ACTIVE    -ErrorAction SilentlyContinue
        Remove-Item Env:LLMSTACK_CHANNEL   -ErrorAction SilentlyContinue
        Remove-Item Env:LLMSTACK_REMOTE_URL -ErrorAction SilentlyContinue
        $global:_LLMSTACK_PROMPT_ON = $false
    }
}

# Wrap the existing prompt once so every prompt cycle re-runs the
# activator and (when inside a project) prefixes the prompt. Idempotent
# via the _LLMSTACK_PROMPT_WRAPPED guard.
if (-not (Get-Variable -Name _LLMSTACK_PROMPT_WRAPPED -Scope Global -ErrorAction SilentlyContinue)) {
    $global:_LLMSTACK_PROMPT_WRAPPED = $true
    $global:_LLMSTACK_ORIG_PROMPT = (Get-Item Function:prompt).ScriptBlock
    function global:prompt {
        _LlmstackActivate
        if ($global:_LLMSTACK_PROMPT_ON) {
            $esc = [char]27
            $color  = $global:_LLMSTACK_PROMPT_COLOR
            $label  = $global:_LLMSTACK_PROMPT_LABEL
            $suffix = $global:_LLMSTACK_PROMPT_SUFFIX
            Write-Host -NoNewline "$esc[38;5;${color}m[llmstack:$label$suffix]$esc[0m "
        }
        & $global:_LLMSTACK_ORIG_PROMPT
    }
}
_LlmstackActivate
# --- end llmstack hook -----------------------------------------------------
"""


def activate_hook(shell: str) -> str:
    """Return the shell-rc snippet for ``shell``.

    Supported: ``zsh``, ``bash``, ``powershell`` / ``pwsh``.
    """
    if shell == "zsh":
        return _ZSH_HOOK
    if shell == "bash":
        return _BASH_HOOK
    if shell in ("powershell", "pwsh"):
        return _POWERSHELL_HOOK
    raise SystemExit(
        f"activate: unknown shell '{shell}' (supported: zsh, bash, powershell)"
    )
