"""Spawn the env-prepared subshell + emit shell activation hooks.

Two distinct UX surfaces live here:

  :func:`spawn_subshell`
    Used by ``llmstack start`` and ``llmstack shell``. ``execvp``s into
    the user's ``$SHELL`` with ``OPENCODE_CONFIG`` and friends exported
    so ``opencode`` -- and any other tool -- picks up our local stack
    inside that one terminal only. For zsh and bash we also write a
    transient rcfile that sources the user's normal rc and prefixes the
    prompt with ``[llmstack:<channel>]``.

  :func:`activate_hook`
    Used by ``llmstack activate <shell>``. Emits a self-contained
    snippet the user pastes into their shell rc once. The snippet walks
    up from ``$PWD`` on every prompt to find the nearest
    ``.llmstack/opencode.json`` and toggles the env vars + prompt
    prefix accordingly. Independent of the spawn flow above.
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

from llmstack.paths import PACKAGE_DIR, remote_url, resolve

# 256-colour palette:
#   current  = steel-blue    (38)   -- our local stack, canonical channel
#   next     = orange        (208)  -- our local stack, queued upgrade channel
#   external = medium-purple (135)  -- thin client of a remote llmstack
#                                      (LLMSTACK_REMOTE_URL is set)
#   shared   = yellow        (220)  -- local daemons we don't own (started
#                                      by another project on this host)
COLOR_CODE = {"current": 38, "next": 208, "external": 135, "shared": 220}


def _user_shell() -> tuple[str, str]:
    """Return (full path to shell, basename like ``zsh``)."""
    user_shell = os.environ.get("LLMSTACK_SHELL") or os.environ.get("SHELL") or "/bin/bash"
    return user_shell, os.path.basename(user_shell)


def _llmstack_alias_target() -> str:
    """Best path to invoke ``llmstack`` from inside the spawned shell.

    Prefers the console-script on ``PATH`` (``pip install`` provides one);
    falls back to ``python -m llmstack`` so an editable / non-console
    install still works.
    """
    found = shutil.which("llmstack")
    if found:
        return found
    return f"{sys.executable} -m llmstack"


def _prompt_label(channel: str, url: str | None) -> str:
    """Text inside ``[llmstack:...]`` -- ``external`` keeps the URL visible."""
    if channel == "external" and url:
        return f"{channel} {url}"
    return channel


def _write_bash_rcfile(rcfile: Path, channel: str, color: int, alias_target: str, label: str) -> None:
    rcfile.write_text(
        "# AUTO-GENERATED by llmstack; sourced by the spawned subshell.\n"
        '[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"\n'
        f"alias llmstack='{alias_target}'\n"
        f'PS1="\\[\\033[38;5;{color}m\\][llmstack:{label}]\\[\\033[0m\\] ${{PS1:-\\$ }}"\n'
    )


def _write_zsh_rcfile(zdotdir: Path, channel: str, color: int, alias_target: str, label: str) -> None:
    zdotdir.mkdir(parents=True, exist_ok=True)
    (zdotdir / ".zshrc").write_text(
        "# AUTO-GENERATED by llmstack; sourced by the spawned subshell.\n"
        '[ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc"\n'
        f"alias llmstack='{alias_target}'\n"
        f'PROMPT="%F{{{color}}}[llmstack:{label}]%f ${{PROMPT:-%# }}"\n'
    )


def spawn_subshell(channel: str, *, reload: bool = False) -> None:
    """Replace the current process with an interactive shell carrying our env.

    Refuses re-entry into a nested llmstack shell unless ``reload=True``
    (used by ``start`` to swap channels in-place).
    """
    paths = resolve()
    if not paths.opencode_json.is_file():
        raise SystemExit(f"missing {paths.opencode_json} (run: llmstack install)")

    if os.environ.get("LLMSTACK_ACTIVE") == "1" and not reload:
        print(
            f"[!] already inside an llmstack shell (channel: {os.environ.get('LLMSTACK_CHANNEL', '?')}).",
            file=sys.stderr,
        )
        print("    exit this shell first if you want to start a new one.", file=sys.stderr)
        raise SystemExit(1)

    user_shell, shell_name = _user_shell()
    color = COLOR_CODE.get(channel, COLOR_CODE["current"])
    alias_target = _llmstack_alias_target()

    rurl = remote_url()
    label = _prompt_label(channel, rurl)
    print()
    print(f"[*] entering llmstack subshell (channel: {channel}, shell: {shell_name})")
    print(f"    OPENCODE_CONFIG -> {paths.opencode_json}")
    if rurl:
        print(f"    remote          -> {rurl}")
    print(f"    alias 'llmstack' -> {alias_target}")
    if channel == "external":
        print("    remote daemons keep running on exit; nothing local to stop.")
    else:
        print("    daemons keep running on exit; stop them with: llmstack stop")
    print("    second window?: llmstack shell")
    print()

    if shell_name == "bash":
        rcfile = paths.state_dir / "llmstack.bashrc"
        _write_bash_rcfile(rcfile, channel, color, alias_target, label)
        argv = [user_shell, "--rcfile", str(rcfile), "-i"]
        env = {**os.environ}
    elif shell_name == "zsh":
        zdotdir = paths.state_dir / "zdotdir"
        _write_zsh_rcfile(zdotdir, channel, color, alias_target, label)
        argv = [user_shell, "-i"]
        env = {**os.environ, "ZDOTDIR": str(zdotdir)}
    else:
        argv = [user_shell, "-i"]
        env = {**os.environ}

    env.update({
        "OPENCODE_CONFIG": str(paths.opencode_json),
        "LLMSTACK_CHANNEL": channel,
        "LLMSTACK_ACTIVE": "1",
        "LLMSTACK_ROOT": str(PACKAGE_DIR),
    })
    if rurl:
        env["LLMSTACK_REMOTE_URL"] = rurl

    os.execvpe(argv[0], argv, env)


# --- activate hooks -------------------------------------------------------

_ZSH_HOOK = r"""# --- llmstack auto-activation hook (zsh) -----------------------------------
# Generated by `llmstack activate zsh`. Walks up from $PWD on each
# directory change to find the nearest .llmstack/opencode.json. Reads the
# project's channel marker (active-channel, falling back to
# default-channel) and exports OPENCODE_CONFIG, LLMSTACK_PROJECT,
# LLMSTACK_CHANNEL, and -- when channel == external -- LLMSTACK_REMOTE_URL.
# Reverses everything when you step out.
#
# Marker file format (one line):
#   <channel>[ <url>]
#
# Prompt colour by channel:
#   current  -> steel-blue    (local stack, canonical)
#   next     -> orange        (local stack, queued upgrade)
#   external -> medium-purple (remote stack via LLMSTACK_REMOTE_URL)
#   shared   -> yellow        (local daemons started by another project)
# In external mode the URL is appended to the prompt label so you always
# see which remote you're talking to: [llmstack:<project> <url>]

_llmstack_find_root() {
    local dir="${1:-$PWD}"
    while [[ "$dir" != "/" && -n "$dir" ]]; do
        if [[ -f "$dir/.llmstack/opencode.json" ]]; then
            print -r -- "$dir"
            return 0
        fi
        dir="${dir:h}"
    done
    return 1
}

_llmstack_color() {
    case "${1:-current}" in
        next)     print -r -- 208 ;;
        external) print -r -- 135 ;;
        shared)   print -r -- 220 ;;
        *)        print -r -- 38  ;;
    esac
}

_llmstack_read_marker() {
    # Read "<channel> [url]" from $1 into _ch / _url. Sets _ch="" on failure.
    _ch=""; _url=""
    [[ -f "$1" ]] || return 0
    read -r _ch _url < "$1" || true
}

_llmstack_activate() {
    local found
    found="$(_llmstack_find_root)" || found=""

    if [[ -n "$found" ]]; then
        # entering or moving within a project
        if [[ "${LLMSTACK_PROJECT:-}" != "$found" ]]; then
            export OPENCODE_CONFIG="$found/.llmstack/opencode.json"
            export LLMSTACK_PROJECT="$found"
            export LLMSTACK_ACTIVE="1"

            local _ch _url
            # Channel resolution: live (active-channel, written by `start`)
            # > intent (default-channel, written by `install`) > "current".
            if [[ -f "$found/.llmstack/active-channel" ]]; then
                _llmstack_read_marker "$found/.llmstack/active-channel"
            else
                _llmstack_read_marker "$found/.llmstack/default-channel"
            fi
            : "${_ch:=current}"
            export LLMSTACK_CHANNEL="$_ch"
            if [[ "$_ch" == "external" && -n "$_url" ]]; then
                export LLMSTACK_REMOTE_URL="$_url"
            else
                unset LLMSTACK_REMOTE_URL
            fi

            : "${_LLMSTACK_PS1_BACKUP:=$PROMPT}"
            export _LLMSTACK_PS1_BACKUP
            local label color suffix
            label="${found:t}"
            color="$(_llmstack_color "$_ch")"
            if [[ "$_ch" == "external" && -n "$_url" ]]; then
                suffix=" $_url"
            else
                suffix=""
            fi
            PROMPT="%F{${color}}[llmstack:${label}${suffix}]%f $_LLMSTACK_PS1_BACKUP"
        fi
    else
        # leaving any project
        if [[ -n "${LLMSTACK_PROJECT:-}" ]]; then
            unset OPENCODE_CONFIG LLMSTACK_PROJECT LLMSTACK_ACTIVE LLMSTACK_CHANNEL LLMSTACK_REMOTE_URL
            if [[ -n "${_LLMSTACK_PS1_BACKUP:-}" ]]; then
                PROMPT="$_LLMSTACK_PS1_BACKUP"
                unset _LLMSTACK_PS1_BACKUP
            fi
        fi
    fi
}

# Hook on every directory change AND once for the current shell.
autoload -U add-zsh-hook
add-zsh-hook chpwd _llmstack_activate
_llmstack_activate
# --- end llmstack hook -----------------------------------------------------
"""

_BASH_HOOK = r"""# --- llmstack auto-activation hook (bash) ----------------------------------
# Generated by `llmstack activate bash`. Walks up from $PWD on each prompt
# to find the nearest .llmstack/opencode.json. Reads the project's channel
# marker (active-channel, falling back to default-channel) and exports
# OPENCODE_CONFIG, LLMSTACK_PROJECT, LLMSTACK_CHANNEL, and -- when
# channel == external -- LLMSTACK_REMOTE_URL. Reverses everything when
# you step out.
#
# Marker file format (one line):
#   <channel>[ <url>]
#
# Prompt colour by channel:
#   current  -> steel-blue    (local stack, canonical)
#   next     -> orange        (local stack, queued upgrade)
#   external -> medium-purple (remote stack via LLMSTACK_REMOTE_URL)
#   shared   -> yellow        (local daemons started by another project)
# In external mode the URL is appended to the prompt label so you always
# see which remote you're talking to: [llmstack:<project> <url>]

_llmstack_find_root() {
    local dir="${1:-$PWD}"
    while [[ "$dir" != "/" && -n "$dir" ]]; do
        if [[ -f "$dir/.llmstack/opencode.json" ]]; then
            printf '%s\n' "$dir"
            return 0
        fi
        dir="$(dirname "$dir")"
    done
    return 1
}

_llmstack_color() {
    case "${1:-current}" in
        next)     printf '%s' 208 ;;
        external) printf '%s' 135 ;;
        shared)   printf '%s' 220 ;;
        *)        printf '%s' 38  ;;
    esac
}

_llmstack_read_marker() {
    _ch=""; _url=""
    [[ -f "$1" ]] || return 0
    read -r _ch _url < "$1" || true
}

_llmstack_activate() {
    local found
    found="$(_llmstack_find_root)" || found=""

    if [[ -n "$found" ]]; then
        if [[ "${LLMSTACK_PROJECT:-}" != "$found" ]]; then
            export OPENCODE_CONFIG="$found/.llmstack/opencode.json"
            export LLMSTACK_PROJECT="$found"
            export LLMSTACK_ACTIVE="1"

            local _ch _url
            # Channel resolution: live > intent > "current" (see zsh hook).
            if [[ -f "$found/.llmstack/active-channel" ]]; then
                _llmstack_read_marker "$found/.llmstack/active-channel"
            else
                _llmstack_read_marker "$found/.llmstack/default-channel"
            fi
            : "${_ch:=current}"
            export LLMSTACK_CHANNEL="$_ch"
            if [[ "$_ch" == "external" && -n "$_url" ]]; then
                export LLMSTACK_REMOTE_URL="$_url"
            else
                unset LLMSTACK_REMOTE_URL
            fi

            : "${_LLMSTACK_PS1_BACKUP:=$PS1}"
            export _LLMSTACK_PS1_BACKUP
            local label color suffix
            label="$(basename "$found")"
            color="$(_llmstack_color "$_ch")"
            if [[ "$_ch" == "external" && -n "$_url" ]]; then
                suffix=" $_url"
            else
                suffix=""
            fi
            PS1="\[\033[38;5;${color}m\][llmstack:${label}${suffix}]\[\033[0m\] $_LLMSTACK_PS1_BACKUP"
        fi
    else
        if [[ -n "${LLMSTACK_PROJECT:-}" ]]; then
            unset OPENCODE_CONFIG LLMSTACK_PROJECT LLMSTACK_ACTIVE LLMSTACK_CHANNEL LLMSTACK_REMOTE_URL
            if [[ -n "${_LLMSTACK_PS1_BACKUP:-}" ]]; then
                PS1="$_LLMSTACK_PS1_BACKUP"
                unset _LLMSTACK_PS1_BACKUP
            fi
        fi
    fi
}

# Bash has no chpwd hook, so we run on every prompt. Idempotent: if the
# project hasn't changed, we no-op.
case ";${PROMPT_COMMAND:-};" in
    *";_llmstack_activate;"*) ;;
    *) PROMPT_COMMAND="_llmstack_activate;${PROMPT_COMMAND:-}" ;;
esac
_llmstack_activate
# --- end llmstack hook -----------------------------------------------------
"""


def activate_hook(shell: str) -> str:
    """Return the shell-rc snippet for ``shell`` (``zsh`` or ``bash``)."""
    if shell == "zsh":
        return _ZSH_HOOK
    if shell == "bash":
        return _BASH_HOOK
    raise SystemExit(f"activate: unknown shell '{shell}' (supported: zsh, bash)")
